### ISSUE TITLE
Problem compiling testcase dht

### ISSUE THREAD

**Issue by lucacampanile3** [libp2p/test-plans#10]
Hi guys, i'm using libp2p testcase for test the performance evaluation of the DHT, i already installed succesfully testground and libp2p testing but when i run the command `testground run single --plan libp2p/dht --testcase find-peers  --builder docker:go --runner local:docker --instances 10` the shell print an unusual error

-- Running in ee5474c9ab62
 github.com/libp2p/test-plans/dht/test
test/common.go:214:34: undefined: getTaggedLibp2pOpts
test/common.go:236:14: undefined: createDHT
test/common.go:759:2: undefined: TableHealth
test/common.go:821:10: undefined: specializedTraceQuery
test/find_providers.go:130:54: undefined: getAllProvRecordsNum
test/tracers.go:77:12: undefined: specializedTraceQuery
Jul 31 17:18:57.547364	INFO	build failed	{"req_id": "e2b68ead", "plan": "dht", "groups": ["single"], "builder": "docker:go", "error": "docker build failed: The command '/bin/sh -c cd ${PLAN_DIR}     && go env -w GOPROXY=\"${GO_PROXY}\"     && GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}' returned a non-zero code: 2"}
Jul 31 17:18:57.547464	WARN	engine build error: docker build failed: The command '/bin/sh -c cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}' returned a non-zero code: 2	{"req_id": "e2b68ead"}
Jul 31 17:18:57.547502	INFO	request handled	{"req_id": "e2b68ead", "command": "build"}

Maybe there is an error with the dependencies in the file common.go am i right?
But i do not touch the code why i have this problem?

Thanks a lot for helping me 

Regards
Luca

**Comment by aschmahmann** [comment]
The DHT plans must be run as compositions in order to have the correct dependencies and build tags. Try using the all-cypress.toml file for example.

**Comment by LucaCampanile** [comment]
> The DHT plans must be run as compositions in order to have the correct dependencies and build tags. Try using the all-cypress-k8s.toml file for example (if you're using k8s) or one the findprovs-both-local.toml (for local docker).
> 
> Local docker cannot really run enough instances to give meaningful results, do I'd recommend a k8s setup for actual analysis

Hi thanks a lot for you reply , i'm trying to use all-cypress-k8s with k8s and findprovs-both-local with docker but when i run  i have the same problem
I'm probably doing something wrong 
Sorry for my unfamiliarity but maybe i'm trying to not run as compositions that's why i'm not able to run?
But how i can run DHT as compositions?

Thanks for your reply help me a lot

**Comment by aschmahmann** [comment]
The `undefined` errors are due to you not using build flags, as the DHT tests were written to simulate multiple versions of the DHT running against each other.

Take a look at the testground documentation https://docs.testground.ai/running-test-plans#executing-a-composition.

Testground has been moving pretty quickly recently and I haven't run this test for a while so it's possible there are some compatibility errors with the latest testground. If so then @nonsense might have more info.

**Comment by LucaCampanile** [comment]
Maybe when i run the command-line `testground run single --plan libp2p/dht --testcase find-peers --builder docker:go --runner local:docker --instances 100` i need to insert the dependency mapping with the command `-dep value` but what value i can insert?
Reading the documentation I came to this intuition but I don't know if I'm right 
I also tried to run my composition with testground documentation but the command line didn't work  because "failed to process composition file: open dht-composition.toml: no such file or directory" but the file exist in the testground folder
Thanks for your reply i hope we'll find a solution

**Comment by Drengot-p2p** [comment]
EDIT: maybe i find a solution for running for `findprovs-both-local.toml ` now it still run thanks to documentation i solved a problem but now i run the problem with " ERROR	Error response from daemon: No such image: f1d89aed47ea:latest	{"req_id": "e8c1efba", "runner": "local:docker", "run_id": "2f05b4ae783e"} ", i open the configuration file `findprovs-both-local` and 
in the composition file there is a  
`  [groups.run] artifact = "f8750a88a49c"` that this is a problem, maybe i need to edit this number but what does it mean group artifact?
Maybe i need to create a group of a containers and insert the id?
Sorry for the asking but in the documentation there isn't information about that
Thanks a lot for your reply

**Comment by nonsense** [comment]
@Drengot-p2p you should remove the `artifact` lines. If you have an `artifact` specified, it means that the composition must be able to find that image and run/execute that artifact - it skips the `build` step.

Since these `artifacts` are not publicly available, you really can't run the composition on your end, without compiling first.

@aschmahmann maybe worth removing the artifacts from the compositions in this repo? WDYT?

**Comment by Drengot-p2p** [comment]
Hi thanks a lot for your reply, i also came to this conclusion and now I have managed to run properly the test, maybe it is really worth removing the artifacts from compositions. Now i run the test with 150 instances, my goal is to analize how much DHT it takes to find a peer that have a content that we search but how i can analyse the DHT performance? There is any documentation about that?  I'm reading the `.out` file that the test produces and when the searcher peer find peer 1 it takes so much
This is a result

> start find peer number 1"}}

> {"ts":1596298008809381199,"msg":"","group_id":"balsam-dialable-provider","run_id":"ef9898ed8734","event":{"type":"metric","metric":{"name":"time-to-peer-0","unit":"ns","dir":-1,"value":5559349002}}}``

> {"ts":1596298026956969033,"msg":"","group_id":"balsam-dialable-provider","run_id":"ef9898ed8734","event":{"type":"metric","metric":{"name":"signal peer-records1","unit":"ns","dir":-1,"value":18143099410}}}

> {"ts":1596298027376790195,"msg":"","group_id":"balsam-dialable-provider","run_id":"ef9898ed8734","event":{"type":"metric","metric":{"name":"barrierpeer-records1","unit":"ns","dir":-1,"value":352946202}}}
> {"ts":1596298027384235989,"msg":"","group_id":"balsam-dialable-provider","run_id":"ef9898ed8734","event":
>{"type":"metric","metric":{"name":"full peer-records1","unit":"ns","dir":-1,"value":24895855261}}}

It is a reasonable result? 5-3 seconds isn't high?
Or I'm wrong read the file .out?
Thanks for you reply

**Comment by p-shahi** [comment]
Moving dht tests out of the repo see https://github.com/libp2p/test-plans/pull/129
