### ISSUE TITLE
Update interop test implementations to conform to...

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/test-plans#120]
to https://github.com/libp2p/test-plans/blob/master/multidim-interop/README.md

Impls:
- [x] Rust https://github.com/libp2p/rust-libp2p/pull/3423
- [ ] Go https://github.com/libp2p/test-plans/pull/121
- [ ] JS( https://github.com/libp2p/test-plans/pull/121

**Comment by jxs** [comment]
Submitted libp2p/rust-libp2p#3423, @thomaseizinger has submitted https://github.com/libp2p/rust-libp2p/pull/3415  ,https://github.com/libp2p/rust-libp2p/pull/3416 and https://github.com/libp2p/rust-libp2p/pull/3417. 

After  libp2p/rust-libp2p#3423 gets merged we can rebase the other PR's against it, publish the images so that we follow https://github.com/libp2p/test-plans/issues/111#issuecomment-1411272771 and then use them in the interop tests wdyt @MarcoPolo ?
