### ISSUE TITLE
Building JS container is slow

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/test-plans#141]
Not fully sure what is going on here but I think the number of layers in the JS Dockerfile seem to take an excessive amount of time.

See https://github.com/libp2p/test-plans/actions/runs/4202681577/jobs/7291145078#step:3:1547.

This is a build where everything is cached, yet it takes a full two minutes to have the image in place.

**Comment by MarcoPolo** [comment]
I think this is just how long it takes to fetch the layers (big layers since we have a chromium build in there).

Looking at https://github.com/libp2p/test-plans/actions/runs/4202681577/jobs/7291145078#step:3:1547

The nodejs build starts at `2023-02-17T22:50:11.6774678Z` and ends at `2023-02-17T22:50:45.0735517Z`. That's 34s.

The chromium build starts at `2023-02-17T22:48:47.3924840Z` and ends at `2023-02-17T22:50:11.7217473Z`. That's a bit shy of two minutes. It has to fetch some big layers like a 500MiB one and a 200MiB one.

So I think the answer here is unfortunately Chromium containers are big

**Comment by thomaseizinger** [comment]
It is the importing and exporting that seems to take significant time: https://github.com/libp2p/test-plans/actions/runs/4202681577/jobs/7291145078#step:3:1567

Do we know what docker is doing there and whether it is necessary?

**Comment by thomaseizinger** [comment]
https://docs.docker.com/build/exporters/ seems to suggest that this is necessary for the containers to be available for docker itself. I am still surprised it is this slow. Copying a few hundred MBs shouldn't take 2min these days ...
