### ISSUE TITLE
interop tests are very slow

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/test-plans#29]
They're by far the slowest workflow in our CI configuration (even though we haven't even started addressing https://github.com/libp2p/go-libp2p/issues/1632, which would further speed up the other workflows).

Just building testground takes more than 5 minutes, see https://github.com/libp2p/go-libp2p/runs/7825338253?check_suite_focus=true. This could easily be cached: either testground itself could provide pre-built binaries / Docker images, or the workflow could cash its results (under the hash of the most recent master commit, so that updates would automatically trigger a rebuild).

Running the composition takes another 12.5 minutes. I'm sure there are also caching opportunities here, but that might be more challenging.

**Comment by laurentsenta** [comment]
@marten-seemann what would be a "good enough" time for the interop tests,
- to test go versions together?
- to test go + rust versions together?

One thing to note, I'm tackling caching the build artifacts at the moment because these might also fix stability issues:
The issues we saw on go-libp2p happened during `go mod download` and `docker pull`.

**Comment by marten-seemann** [comment]
Do I understand correctly that this is the step that failed? https://github.com/libp2p/test-plans/blob/072d351a5fe0f558d3c5c50eedb952e8159d41a2/.github/workflows/run-composition.yml#L57-L62

Would using one of the GitHub Actions that does automatic retries be an option? For example this one: https://github.com/marketplace/actions/retry-step. (There might be better ones, we'd have to research a bit, this one just showed up as the first search result).

**Comment by laurentsenta** [comment]
Yes, the only failure we saw happened during the build, that's a discussion related to https://github.com/libp2p/go-libp2p/issues/1670 and https://github.com/testground/testground/issues/1422.

We can add retries and different timeouts now that we can split the build & run steps in Testground, but the thing is:

I need to know the "good enough" time, because adding retries will decrease the number of false-negative detected by the CI, but it will also increase the average time it takes to run the interop tests.
Which is between 15 minutes (go-interop) and 30 min (go + rust interop) atm.

**Comment by marten-seemann** [comment]
> Adding retries will decrease the number of false-negative detected by the CI, but it will also increase the average time it takes to run the interop tests. Which is between 15 minutes (go-interop) and 30 min (go + rust interop) atm.

Is it possible to build incrementally? If I understand correctly, `testground build composition` builds _all_ runners (?) required in that test case. If there was a way to build them one by one, the cost for a retyr when one of them fails would be much lower.

Alternatively, `testground build composition` could contain the retry logic.
